version: 2.1
commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>
      
job:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
    
workflow:
  my_workflow:
    jobs:
      - my_job
